export { default as ButtonComp } from "./Button"
export { default as buttonTransparenteComp } from "./ButtonOpacity"
export { default as CardSocialComp } from "./CardSocial"
export { default as CardComp } from "./Card"
export { default as LoadingComp } from "./Loading"